name: analogweb core CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          cache: maven
          distribution: 'temurin'
      - name: Code Format Validation
        run: mvn formatter:validate
      - name: Test
        run: mvn clean test
